output {
  # Console for debugging
  stdout {
    codec => rubydebug
  }

  # OpenSearch
  elasticsearch {
    hosts => ["opensearch:9200"]
    index => "security-events-%{+YYYY.MM.dd}"
    document_id => "%{[event][hash]}"
    action => "index"
    manage_template => false
  }
}
