# Logstash Outputs — OpenSearch
output {
  elasticsearch {
    hosts => ["10.0.0.10:9200", "10.0.0.11:9200", "10.0.0.12:9200"]
    index => "security-events-%{+YYYY.MM.dd}"
    document_id => "%{[event][hash]}"
    action => "index"
    manage_template => false
    template_overwrite => false
  }

  # stdout debugging (disabled in production)
  # stdout { codec => rubydebug }
}
